export default defineEventHandler( async () => {
    await new Promise(resolve => setTimeout(resolve, 100))
    return [
        {
            id: 1,
            name: 'Quaomiuzzaman Kabbya',
            phone: '01721597157',
            img: 'imgs/cricket.png',
            users: '50 Active 3',
            earning: '400 Taka',
            rate: '40%',
        },
        {
            id: 2,
            name: 'Tanvir Ahmed',
            phone: '01711122334',
            img:'imgs/cricket.png',
            users: '30 Active 2',
            earning: '300 Taka',
            rate: '35%',
        },
        {
            id: 3,
            name: 'Rafiul Islam',
            phone: '01811223344',
            img: 'imgs/cricket.png',
            users: '40 Active 5',
            earning: '450 Taka',
            rate: '42%',
        },
        {
            id: 4,
            name: 'Nahid Hasan',
            phone: '01611223344',
            img: 'imgs/cricket.png',
            users: '45 Active 6',
            earning: '380 Taka',
            rate: '38%',
        },
        {
            id: 5,
            name: 'Farhan Jamil',
            phone: '01799887766',
            img: 'imgs/cricket.png',
            users: '60 Active 4',
            earning: '500 Taka',
            rate: '50%',
        },
        {
            id: 6,
            name: 'Ashiqur Rahman',
            phone: '01922334455',
            img: 'imgs/user6.png',
            users: '25 Active 2',
            earning: '280 Taka',
            rate: '30%',
        },
        {
            id: 7,
            name: 'Mehedi Hasan',
            phone: '01522334455',
            img: 'imgs/cricket.png',
            users: '55 Active 5',
            earning: '470 Taka',
            rate: '48%',
        },
        {
            id: 8,
            name: 'Jubayer Rahman',
            phone: '01312345678',
            img: 'imgs/cricket.png',
            users: '35 Active 3',
            earning: '320 Taka',
            rate: '36%',
        },
        {
            id: 9,
            name: 'Naimur Rahman',
            phone: '01744556677',
            img: 'imgs/cricket.png',
            users: '38 Active 2',
            earning: '350 Taka',
            rate: '37%',
        },
        {
            id: 10,
            name: 'Shahriar Kabir',
            phone: '01999887766',
            img: 'imgs/cricket.png',
            users: '48 Active 6',
            earning: '410 Taka',
            rate: '41%',
        },
    ];
});